spring:
    application:
        name: sales_tracker
    datasource:
        url: jdbc:postgresql://localhost:5432/TESTDB
        username: postgres
        password: postgres
        hikari:
            connectionTimeout: 30000
            maximumPoolSize: 10
            maxLifetime: 30000
            idleTimeout: 30000
            validationTimeout: 30000
            initializationFailTimeout: 30000
logging:
    level:
        root: INFO
        com:
            mbb: DEBUG

# device:
#     brands:
#         url: https://script.google.com/macros/s/AKfycbxNu27V2Y2LuKUIQMK8lX1y0joB6YmG6hUwB1fNeVbgzEh22TcDGrOak03Fk3uBHmz-/exec?route=brand-list
#     search:
#         url: https://script.google.com/macros/s/AKfycbxNu27V2Y2LuKUIQMK8lX1y0joB6YmG6hUwB1fNeVbgzEh22TcDGrOak03Fk3uBHmz-/exec
device:
    datasource:
        url: https://script.google.com/macros/s/AKfycbxNu27V2Y2LuKUIQMK8lX1y0joB6YmG6hUwB1fNeVbgzEh22TcDGrOak03Fk3uBHmz-/exec
