spring:
    datasource:
        url: jdbc:postgresql://<PRODUCTION_DB_URL>:5432/sales
        username: <PRODUCTION_DB_USERNAME>
        password: <PRODUCTION_DB_PASSWORD>
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
    security:
        user:
            username: produser
            password: prodpassword
logging:
    file:
        path: ./logs
    level:
        root: INFO
        com.mbb.api.sales_tracker: INFO
        org.springframework.web: INFO
        org.springframework.security: INFO
scheduler:
    brands:
        expression: "0 00 00 * * *"