spring:
    datasource:
        url: jdbc:postgresql://<awsrds>:5432/sales
        username: developer
        password: postgres
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true
        locations: classpath:db/migration