spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sales
        username: developer
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    flyway:
        enabled: true
        locations: classpath:db/migration